language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install libconfuse-dev
  - sudo apt-get install libnl-3-dev libnl-route-3-dev
  - sudo apt-get install libncurses-dev
  - sudo apt-get install libiw-dev
# Change this to your needs
script: ./.travis/run.sh
